name: Build for Ubuntu 18.04 and ROS Melodic

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ros:melodic

    defaults:
      run:
        shell: bash -leo pipefail {0}

    steps:
      - name: Create catkin workspace
        run:
          mkdir $GITHUB_WORKSPACE/catkin_ws/src -p ;
          cd $GITHUB_WORKSPACE/catkin_ws;
          source /opt/ros/melodic/setup.bash;
          catkin_make;

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: catkin_ws/src/
      
      - name: Install CMake 3.16
        run: |
          apt install build-essential libssl-dev wget git -y
          wget https://github.com/Kitware/CMake/releases/download/v3.16.3/cmake-3.16.3.tar.gz
          tar -zxvf cmake-3.16.3.tar.gz
          cd cmake-3.16.3
          ./bootstrap
          make 
          make install 

      - name: Build package
        run: |
          export DEBIAN_FRONTEND=noninteractive
          cd $GITHUB_WORKSPACE/catkin_ws;
          source /opt/ros/melodic/setup.bash;
          apt update && rosdep update && rosdep install --from-paths src/ -y -r;
          catkin_make;

      - name: Execute tests 
        run: |
          source /opt/ros/noetic/setup.bash;
          source $GITHUB_WORKSPACE/catkin_ws/devel/setup.bash
          rosrun heuristic_planners main_test
        



        